<?xml version="1.0"?>

<!-- Caster link xacro -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="caster" params="prefix reflect">

    <link name="${prefix}_caster">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <sphere radius="${caster_radius}" />
        </geometry>
        <material name="black"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <sphere radius="${caster_radius}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="0.01" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0"
                 izz="0.001" />
        </inertial>
    </link>
    <joint name="${prefix}_caster_joint" type="fixed">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_caster"/>
      <origin xyz="${(casterbase + caster_radius) * reflect / 2}
                   0
                   ${caster_offset - caster_radius}"
              rpy="0 0 0"/>
    </joint>

    <gazebo reference="${prefix}_caster">
      <mu1>0.0</mu1>
      <mu2>0.0</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>1.0</maxVel>
      <material>grey</material>
    </gazebo>

  </xacro:macro>
</robot>
