<?xml version="1.0"?>
<robot name="goldorak" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="body_radius" value="0.12" />
  <xacro:property name="body_height" value="0.4" />
  <xacro:property name="wheelbase" value="0.194" />
  <xacro:property name="wheel_radius" value="0.029" />
  <xacro:property name="wheel_thickness" value="0.01" />
  <xacro:property name="wheel_offset" value="-0.15" />
  <xacro:property name="casterbase" value="0.194" />
  <xacro:property name="caster_radius" value="0.01" />
  <xacro:property name="caster_offset" value="-0.19" />

  <xacro:include filename="$(find goldorak_description)/urdf/common.urdf.xacro" />
  <xacro:include filename="$(find goldorak_description)/urdf/wheel.urdf.xacro" />
  <xacro:include filename="$(find goldorak_description)/urdf/caster.urdf.xacro" />

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${body_radius}" length="${body_height}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${body_radius}" length="${body_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2" />
      <origin xyz="0 0 0.0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.5" />
    </inertial>
  </link>

  <!-- Wheels -->
  <xacro:wheel prefix="right" reflect="1"/>
  <xacro:wheel prefix="left" reflect="-1"/>

  <!-- Casters -->
  <xacro:caster prefix="front" reflect="1"/>
  <xacro:caster prefix="rear" reflect="-1"/>

  <!-- Laser scanner 1D link -->
  <joint name="laser_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${body_height / 2}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="laser_link"/>
  </joint>

  <link name="laser_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.02" length="0.02"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.02" length="0.02"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0"
               iyy="1e-6" iyz="0"
               izz="1e-6" />
    </inertial>
  </link>

  <!-- Gazebo plugin for ROS Control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>

  <!-- Gazebo plugin for Laser scanner -->
  <gazebo reference="laser_link">
    <sensor type="ray" name="laser_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>1</samples>
            <resolution>1</resolution>
            <min_angle>-1.570796</min_angle>
            <max_angle>1.570796</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_laser_controller" filename="libgazebo_ros_laser.so">
        <topicName>/laser/scan</topicName>
        <frameName>laser_link</frameName>
      </plugin>
    </sensor>
  </gazebo>
</robot>
