<?xml version="1.0"?>
<robot name="goldorak" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="body_radius" value="0.12" />
  <xacro:property name="body_height" value="0.4" />
  <xacro:property name="wheelbase" value="0.194" />
  <xacro:property name="wheel_radius" value="0.029" />
  <xacro:property name="wheel_thickness" value="0.01" />
  <xacro:property name="wheel_offset" value="-0.15" />
  <xacro:property name="casterbase" value="0.194" />
  <xacro:property name="caster_radius" value="0.01" />
  <xacro:property name="caster_offset" value="-0.19" />

  <xacro:include filename="$(find goldorak_description)/urdf/common.urdf.xacro" />
  <xacro:include filename="$(find goldorak_description)/urdf/wheel.urdf.xacro" />
  <xacro:include filename="$(find goldorak_description)/urdf/caster.urdf.xacro" />
  <xacro:include filename="$(find goldorak_description)/urdf/range_sensor.urdf.xacro" />

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${body_radius}" length="${body_height}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${body_radius}" length="${body_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2" />
      <origin xyz="0 0 0.0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.5" />
    </inertial>
  </link>

  <!-- Wheels -->
  <xacro:wheel prefix="right" reflect="1"/>
  <xacro:wheel prefix="left" reflect="-1"/>

  <!-- Casters -->
  <xacro:caster prefix="front" reflect="1"/>
  <xacro:caster prefix="rear" reflect="-1"/>

  <!-- Gazebo plugin for ROS Control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>

  <!-- Laser scanner 1D link -->
  <xacro:range_sensor name="laser" parent="base_link" rate="50"
                      maxRange="4.0" minRange="0.15" fov="0.1">
    <origin xyz="0 0 ${body_height / 2}" rpy="0 0 0"/>
  </xacro:range_sensor>

</robot>
